{{- /* External Secret Template */}}

{{- range $name, $secret := $.Values.secrets }}
---
# External Secret:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  # namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels: {{- include "skware.labels" $ | nindent 4 }}
  annotations:
    {{- /* Ensuring External Secrets are deployed before the main chart */}}
    argocd.argoproj.io/sync-wave: "-1"
spec:
  # refreshInterval: 1h
  secretStoreRef:
    kind: {{ index $secret "store-kind" | default "ClusterSecretStore" }}
    name: {{ index $secret "store-name" | default "vault" }}
  # Secret to create
  target:
    name: {{ $name }}
    {{- if $secret.template }}
    template: {{ toYaml $secret.template | nindent 6 }}
    {{- end }}
  {{- if $secret.data }}
  data: {{ toYaml $secret.data | nindent 4 }}
  {{- end }}
  {{- if $secret.dataFrom }}
  dataFrom: {{ toYaml $secret.dataFrom | nindent 4 }}
  {{- end }}
{{- end }}
