---
# ArgoCD Self-Managed + Apps health patch
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # Patched installation of ArgoCD
    - repoURL: https://github.com/skware-dev/skware.git
      path: argo-cd
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    # automated:
    #   selfHeal: true
    #   prune: true
