---

# Patched ArgoCD Application to enable Apps health assessment
# cf. https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches:
  - path: app-health-patch.yaml
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ARGOCD_SYNC_WAVE_DELAY
          value: "5"
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
      labelSelector: "app.kubernetes.io/name=argocd-server"
